=== mateomate1/AADD/RA1_XML_DOM2/alumnos4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xsd:element name="estudiantes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="alumno" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="edad" type="xsd:integer"/>
            </xsd:sequence>
            <xsd:attribute name="exp" type="xsd:string" use="required"/>
            <xsd:attribute name="nombre" type="xsd:string" use="optional"/>
			<xsd:attribute name="edad" type="xsd:integer" use="optional"/>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== mateomate1/AADD/RA1_XML_DOM2/alumnos4.xml
<?xml version="1.0" encoding="UTF-8"?>
<estudiantes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="alumnos4.xsd">
  <alumno edad="21" exp="11111" nombre="carlitos">
        <edad>21</edad>
    </alumno>
    <alumno edad="28" exp="22222" nombre="menganito">
        <edad>28</edad>
    </alumno>
    <alumno edad="123" exp="33333" nombre="fermin">
        <edad>123</edad>
    </alumno>
    <alumno edad="23" exp="44444" nombre="julito">
        <edad>23</edad>
    </alumno>
</estudiantes>
