=== mateomate1/AADD/ejercicio-gpt-json-xml/empresa.dtd
<!ELEMENT empresa (nombre, empleados, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (nombre, puesto, salario)>
<!ATTLIST empleado id CDATA #REQUIRED>
<!ELEMENT puesto (#PCDATA)>
<!ELEMENT salario (#PCDATA)>
<!ELEMENT direccion (calle, ciudad)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>

=== mateomate1/AADD/ejercicio-gpt-json-xml/datos.xml
<!DOCTYPE empresa SYSTEM "empresa.dtd">
<empresa>
  <nombre>Acme S.A.</nombre>
  <empleados>
    <empleado id="1">
      <nombre>Ana Lopez</nombre>
      <puesto>Desarrollador</puesto>
      <salario>25000</salario>
    </empleado>
    <empleado id="2">
      <nombre>Pablo Ruiz</nombre>
      <puesto>Disenador</puesto>
      <salario>22000</salario>
    </empleado>
  </empleados>
  <direccion>
    <calle>Calle Falsa 123</calle>
    <ciudad>Madrid</ciudad>
  </direccion>
</empresa>
